### PR TITLE
async: fix re_async_cancel mqueue handling

### LINKED ISSUE #992: async_work: worker callback is called twice
Observed this with baresip selftest in branch https://github.com/cspiel1/baresip/tree/rx_thread_activate, e.g. when executing these two tests in a row
```
./test/selftest test_call_rtcp test_call_rtp_timeout
```
then, not always but often I get:
```
==9791== Invalid read of size 8
==9791==    at 0x4894A17: async_work_main (rtprecv.c:741)
==9791==    by 0x48E3CC1: queueh (async.c:150)
==9791==    by 0x490D643: event_handler (mqueue.c:87)
==9791==    by 0x4909ACC: fd_poll (main.c:921)
==9791==    by 0x4909DD5: re_main (main.c:1059)
==9791==    by 0x13CF7F: re_main_timeout (test.c:39)
==9791==    by 0x117270: test_call_rtp_timeout_base (call.c:1001)
==9791==    by 0x117645: test_call_rtp_timeout (call.c:1024)
==9791==    by 0x13D2F8: run_one_test (main.c:86)
==9791==    by 0x13D8CE: main (main.c:273)
==9791==  Address 0x966e3e8 is 200 bytes inside a block of size 440 free'd
==9791==    at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==9791==    by 0x490C7E4: mem_deref (mem.c:390)
==9791==    by 0x4894AF3: async_work_main (rtprecv.c:763)
==9791==    by 0x48E3CC1: queueh (async.c:150)
==9791==    by 0x490D643: event_handler (mqueue.c:87)
==9791==    by 0x4909ACC: fd_poll (main.c:921)
==9791==    by 0x4909DD5: re_main (main.c:1059)
==9791==    by 0x13CF7F: re_main_timeout (test.c:39)
==9791==    by 0x1296F6: test_call_rtcp_base (call.c:2619)
==9791==    by 0x129A0C: test_call_rtcp (call.c:2648)
==9791==    by 0x13D2F8: run_one_test (main.c:86)
==9791==    by 0x13D8CE: main (main.c:273)
```
Which states that `test_call_rtcp` creates the async work and the callback (for the result) is called during next test `test_call_rtp_timeout`. Are there multiple bugs?
- The `mqueue` of `re_async` is not cleared by `re_async_cancel(async, id)`. A simple clear would not be correct, because the `id` has to be respected.
- More general (maybe better suited as baresip issue): How should selftest use `libre_init()`, `libre_close()` resp. `re_thread_async_init()`, `re_thread_async_close()` in order to have each test independent from previous?
-  Or should we add a function `libre_flush(void)` that flushes the complete mainloop, clears all async worker and clears all file descriptor handlers?

### PR DESCRIPTION
**Pull request by sreimers**
Since we can't clear/revert a mqueue_push, free list handling has always be done by async `queueh` and not within `re_async_cancel`. Otherwise job is reused and maybe executed twice or early.

fixes #992

### CODE REVIEW

File: src/async/async.c [hunk 1]
```diff
@@ -351,7 +351,8 @@ void re_async_cancel(struct re_async *async, intptr_t id)
 		w->workh = NULL;
 		w->cb	 = NULL;
 		w->arg	 = mem_deref(w->arg);
-		list_move(&w->le, &async->freel);
+		/* No move to free list since queueh must always handled if
+		 * mqueue_push is called */
```
Comment (cspiel1) [inline src/async/async.c:355]: I can't see why this change has something to do if the pipe is read or not.

Comment (sreimers) [reply src/async/async.c:355]: Pipe queueh is always executed (since it's FIFO), so the free list move must be done there.
