### PR TITLE
ice: AI_V4MAPPED doesn't exist on OpenBSD

### LINKED ISSUE #988: no AI_V4MAPPED define on OpenBSD
updating re to 3.6.0 on OpenBSD, build fails because of the addition in #934 of the use of AI_V4MAPPED which doesnt exist on OpenBSD, there's no support for automagic mapping of v6 to v4 addresses. would an ifdef be accepted ?

### PR DESCRIPTION
**Pull request by landryb**
fixes #988

### CODE REVIEW

File: src/ice/icesdp.c [hunk 1]
```diff
@@ -209,7 +209,11 @@ static int getaddr_rcand(void *arg)
 {
 	struct rcand *rcand = arg;
 	struct addrinfo *res, *res0 = NULL;
+#ifndef __OpenBSD__
```
Comment (sreimers) [inline src/ice/icesdp.c:212]: Please use `OPENBSD` here

**Comment by sreimers** [comment]
Thanks!
